Expose direct configuration of max in and out buffer capacity
paritytech/jsonrpc pull request #594
Opened 2020-10-01 02:43 UTC by emostov

Closes #590, see issue for feature description.

If not set, `max_in_buffer_capacity` and `max_out_buffer_capacity` explicitly defaults to 10,485,760, which is the same as [`parity-ws` `Settings::default`](https://github.com/paritytech/ws-rs/blob/be4d47575bae55c60d9f51b47480d355492a94fc/src/lib.rs#L254).

2020-10-01 06:51 UTC, dvdplm requested changes
Looks good, let's add a test?

2020-10-01 07:52 UTC, niklasad1 commented on ws/src/server_builder.rs
> +			self.max_in_buffer_capacity,
```suggestion
			self.max_out_buffer_capacity,
```

2020-10-01 18:19 UTC, emostov commented
@niklasad1, @maciejhirsz, @dvdplm - added some basic tests. I originally was going to assert every config value, but I could not think of a zero overhead way around the fact some of the more complex types don't support equality comparisons. It also looks like those complex types are tested implicitly in some of the higher level tests so I think that means technically they are covered. 

Unrelated to the tests, I realized this PR may break the API since it changes the defaults for `max_in_buffer_capacity` and `max_out_buffer_capacity`. Previously they defaulted to 5,242,880 (the default of `max_payload_bytes`), now they default to `10,485,760`.

2020-10-01 20:53 UTC, niklasad1 commented
IMO, the tests are sufficient for this change

> Previously they defaulted to 5,242,880 (the default of max_payload_bytes), now they default to 10,485,760

Ok, basically because `ws-rs` defaults `max_buffer_i/o_size` 10MB it's used here too but configured explicitly, otherwise please explain?!

If we want to go with 10MB instead it would be reasonable to use it for `max_payload_bytes` too?

However, I'm not familiar with the reasoning about these limits but 5MB should cover most use-cases AFAIK but perhaps @maciejhirsz or @tomusdrw could explain the reasoning about these limits :)

2020-10-02 11:01 UTC, tomusdrw commented
> However, I'm not familiar with the reasoning about these limits but 5MB should cover most use-cases AFAIK but perhaps @maciejhirsz or @tomusdrw could explain the reasoning about these limits :)

I can't remember exactly, but wasn't this the same limit as `ws-rs` was setting? If not then the values are probably arbitrary, fine to change them to whatever, obv with semver compliance.

2020-10-02 13:09 UTC, maciejhirsz approved these changes

2020-10-02 13:16 UTC, maciejhirsz commented
For the record, the default 10mb limit in `ws-rs`/`parity-ws` is there just so that we don't have an unlimited default. I didn't do any science for it, it should be high enough to make everyday regular use work without issues, so I figured it's better to err on the larger size rather than smaller as long as it doesn't crash things.

2020-10-03 17:32 UTC, emostov commented
Just need one more approval :)

2020-10-05 09:00 UTC, niklasad1 commented
@dvdplm: can you take a look at this again?

2020-10-05 09:24 UTC, dvdplm approved these changes

2020-10-05 09:25 UTC, merged